version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - SQLALCHEMY_DATABASE_URL=postgresql+psycopg2://postgres:567234@db:5432/hw02
  db:
    image: "postgres:12"
    environment:
      - POSTGRES_PASSWORD=567234
      - POSTGRES_DB=hw02
    ports:
      - "5432:5432"